[package]
name = "custom-labels"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
keywords = ["profiling", "pprof", "polarsignals", "parca"]
description = "Custom labels for profilers"
homepage = "https://polarsignals.com"
repository = "https://github.com/umanwizard/custom-labels"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.69"
cc = "1.0"

[dev-dependencies]
rand = "0.8.5"

[dependencies]
libc = "0.2"
