[package]
name = "custom-labels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.69"
cc = "1.0"

[dev-dependencies]
rand = "0.8.5"

[dependencies]
libc = "0.2"
